import { defineConfig } from 'vitepress'

export default defineConfig({
  lang: 'ja',
  title: 'Livewire 4 日本語ドキュメント',
  description: 'Livewire 4 公式ドキュメントの非公式日本語版',
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: 'ホーム', link: '/' },
      { text: 'ドキュメント', link: '/quickstart' },
      { text: '公式Docs', link: 'https://livewire.laravel.com/docs/4.x/quickstart' },
    ],
    sidebar: [
      {
        text: 'はじめに',
        items: [
          { text: 'クイックスタート', link: '/quickstart' },
          { text: 'インストール', link: '/installation' },
          { text: 'アップグレードガイド', link: '/upgrading' },
        ],
      },
      {
        text: '基本',
        items: [
          { text: 'コンポーネント', link: '/components' },
          { text: 'ページ', link: '/pages' },
          { text: 'プロパティ', link: '/properties' },
          { text: 'アクション', link: '/actions' },
          { text: 'フォーム', link: '/forms' },
          { text: 'イベント', link: '/events' },
          { text: 'ライフサイクルフック', link: '/lifecycle-hooks' },
          { text: 'コンポーネントのネスト', link: '/nesting' },
          { text: 'テスト', link: '/testing' },
        ],
      },
      {
        text: '機能',
        items: [
          { text: 'Alpine', link: '/alpine' },
          { text: 'スタイル', link: '/styles' },
          { text: 'ナビゲーション', link: '/navigate' },
          { text: 'Island', link: '/islands' },
          { text: '遅延読み込み', link: '/lazy' },
          { text: 'ローディング状態', link: '/loading-states' },
          { text: 'バリデーション', link: '/validation' },
          { text: 'ファイルアップロード', link: '/uploads' },
          { text: 'ページネーション', link: '/pagination' },
          { text: 'URLクエリパラメータ', link: '/url' },
          { text: '算出プロパティ', link: '/computed-properties' },
          { text: 'リダイレクト', link: '/redirecting' },
          { text: 'ファイルダウンロード', link: '/downloads' },
          { text: 'Teleport', link: '/teleport' },
        ],
      },
      {
        text: 'HTMLディレクティブ',
        items: [
          { text: 'wire:bind', link: '/wire-bind' },
          { text: 'wire:click', link: '/wire-click' },
          { text: 'wire:submit', link: '/wire-submit' },
          { text: 'wire:model', link: '/wire-model' },
          { text: 'wire:loading', link: '/wire-loading' },
          { text: 'wire:navigate', link: '/wire-navigate' },
          { text: 'wire:current', link: '/wire-current' },
          { text: 'wire:cloak', link: '/wire-cloak' },
          { text: 'wire:dirty', link: '/wire-dirty' },
          { text: 'wire:confirm', link: '/wire-confirm' },
          { text: 'wire:transition', link: '/wire-transition' },
          { text: 'wire:init', link: '/wire-init' },
          { text: 'wire:intersect', link: '/wire-intersect' },
          { text: 'wire:poll', link: '/wire-poll' },
          { text: 'wire:offline', link: '/wire-offline' },
          { text: 'wire:ignore', link: '/wire-ignore' },
          { text: 'wire:ref', link: '/wire-ref' },
          { text: 'wire:replace', link: '/wire-replace' },
          { text: 'wire:show', link: '/wire-show' },
          { text: 'wire:sort', link: '/wire-sort' },
          { text: 'wire:stream', link: '/wire-stream' },
          { text: 'wire:text', link: '/wire-text' },
        ],
      },
    ],
    outline: 2,
    socialLinks: [
      { icon: 'github', link: 'https://github.com/yama/livewire4-docs-ja' },
    ],
    footer: {
      message: 'Livewire 公式プロジェクトによる公式日本語版ではありません。',
      copyright: 'Copyright © Caleb Porzio. Japanese translation is unofficial.',
    },
  },
})
